## Задание 1

Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

    если источник traffic_source равен yandex или google, то в source_type ставится organic
    для источников paid и email из России - ставим ad
    для источников paid и email не из России - ставим other
    все остальные варианты берем из traffic_source без изменений

In [5]:
# "Компактный вариант" - спасибо google!

import pandas as pd

data = pd.read_csv('visit_log.csv', sep=';')
#data.head()

data['source_type'] = data['traffic_source']
data.loc[data['traffic_source'].isin(['yandex','google']), 'source_type'] = 'organic'
data.loc[(data['region'] == 'Russia') & (data['traffic_source'].isin(['paid','email'])),'source_type'] = 'ad'
data.loc[(data['region'] != 'Russia') & (data['traffic_source'].isin(['paid','email'])),'source_type'] = 'other'

data.head()

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic

In [11]:
#Вариант решения "долгий", на основе лекции

import pandas as pd

data = pd.read_csv('visit_log.csv', sep=';')
#data.head()

data[ data['visit_id'].str.contains('3c', case = False) ].head()

src1 = ['yandex', 'google']
src2 = ['paid', 'email']

for traffic_source in src1: 
    data.loc[data.traffic_source == traffic_source, 'traffic_type'] = 'organic' 
for traffic_source in src2: 
    data.loc[(data.traffic_source == traffic_source) & (data.region == 'Russia'), 'traffic_type'] = 'ad' 
for traffic_source in src2: 
    data.loc[(data.traffic_source == traffic_source) & (data.region != 'Russia'), 'traffic_type'] = 'other' 
data.loc[pd.isnull(data.traffic_type), 'traffic_type'] = data.traffic_source

result = data[data['visit_id'].str.contains('3c', case = False)]  
result.head()

,timestamp,visit_id,url,region,user_id,traffic_source,traffic_type
35,1549980908,0d5535e13c,https://host.ru/8880fd00cf23066541,Russia,51baf057bb,email,ad
39,1549980932,94c11ed3c3,https://host.ru/da83c74e35e7806fe0,Russia,1875754379,yandex,organic
82,1549981192,10cc3c382b,https://host.ru/c2382eb3d6afc8d0f3,Ukraine,9644780b17,direct,direct
105,1549981369,523c41464e,https://host.ru/05e41944dd85a900a6,Australia,4f40719179,email,other
115,1549981432,23cd67852a,https://host.ru/6fda01ec57f23abc9e,Belarus,4a0f5111cd,google,organic

## Задание 2
В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:

Прочитайте содержимое файла с датафрейм
Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [26]:
import pandas as pd

url = pd.read_csv('URLs.txt')

regex = '/[0-9]{8}-'

result = url[url['url'].str.contains(regex, regex = True)]
result.head()

                                                 url
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...

## Задание 3

В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [21]:
import pandas as pd
from pymystem3 import Mystem

data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

def lemmas_tool(value):
    lemmas = Mystem().lemmatize(value)
    return ' '.join(lemmas).strip()

data['lemmas'] = data['keyword'].apply(lemmas_tool)

data.head()

                 keyword   shows                     lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль
1        доллары в рубли  114173         доллар   в   рубль
2  100 долларов в рублях   97534   100   доллар   в   рубль
3             курс рубля   53546               курс   рубль